## Кросплатформне програмування Python
### Ілларіонов Микита
*ІПЗ 23007б*
**Варіант 5**

## Завдання 1.

$$z_{1}=1-\frac{1}{4}\sin^{2}(2\alpha)+\cos(2\alpha)$$
$$z_{2}=\cos^{2}(\alpha)+\cos^{4}(\alpha)$$

In [1]:
import numpy as np


alpha = np.pi / 6 

z1 = 1 - (1/4) * (np.sin(2 * alpha)**2) + np.cos(2 * alpha)

z2 = (np.cos(alpha)**2) + (np.cos(alpha)**4)

print(f"Заданий параметр alpha: {alpha}")
print(f"Результат z1: {z1}")
print(f"Результат z2: {z2}")

Заданий параметр alpha: 0.5235987755982988
Результат z1: 1.3125
Результат z2: 1.3125000000000002


## Завдання 2.

$$\ln\left(\frac{1+x}{1-x}\right) = 2\sum_{n=0}^{\infty}\frac{x^{2n+1}}{2n+1} = 2\left(x+\frac{x^{3}}{3}+\frac{x^{5}}{5}+...\right), \quad |x| < 1$$

In [2]:
import numpy as np

x = 0.5  # Значення x має бути |x| < 1
eps = 1e-6  # Точність (наприклад, 6 знаків після коми)

# Спосіб 1: Обчислення за допомогою вбудованої функції numpy
math_result = np.log((1 + x) / (1 - x))

# Спосіб 2: Обчислення за допомогою суми ряду
series_result = 0
n = 0
term = 2 * (x**(2*n + 1)) / (2*n + 1) # Перший член ряду

# Цикл працює, поки член ряду більший за задану точність
while abs(term) >= eps:
    series_result += term
    n += 1
    term = 2 * (x**(2*n + 1)) / (2*n + 1) # Наступний член ряду


print(f"Задані параметри: x = {x}, точність = {eps}")
print(f"Значення, пораховане першим способом (NumPy): {math_result:.6f}")
print(f"Значення, пораховане другим способом (Сума ряду): {series_result:.6f}")
print(f"Кількість підсумованих членів ряду: {n}")

Задані параметри: x = 0.5, точність = 1e-06
Значення, пораховане першим способом (NumPy): 1.098612
Значення, пораховане другим способом (Сума ряду): 1.098611
Кількість підсумованих членів ряду: 8


## Завдання 3.

Дано цілочислову квадратну матрицю розмірності 12х12. Матрицю задати в коді програми. Генератор випадкових чисел не використовувати.

Визначити:
1) суму елементів у тих стовпцях, які не містять від'ємних елементів;
2) мінімум серед сум модулів елементів діагоналей, паралельних побічній діагоналі матриці.

In [3]:
import numpy as np

matrix = np.array([
    [ 1,  2, -3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
    [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
    [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
    [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
    [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
    [ 6,  7,  8,  9, 10,-11, 12, 13, 14, 15, 16, 17],
    [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
    [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
    [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
    [11, 12,-13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
])

print("Початкова матриця:")
print(matrix)

cols_without_negatives = np.all(matrix >= 0, axis=0)
valid_cols_sum = np.sum(matrix[:, cols_without_negatives], axis=0)
total_valid_sum = np.sum(valid_cols_sum)

print(f"\n1) Суми в стовпцях без від'ємних елементів: {valid_cols_sum}")
print(f"Загальна сума елементів у цих стовпцях: {total_valid_sum}")

flipped_matrix = np.fliplr(matrix)
abs_matrix = np.abs(flipped_matrix)

min_diag_sum = float('inf')

for k in range(-abs_matrix.shape[0] + 1, abs_matrix.shape[1]):
    current_diag = np.diagonal(abs_matrix, offset=k)
    current_sum = np.sum(current_diag)
    if current_sum < min_diag_sum:
        min_diag_sum = current_sum

print(f"\n2) Мінімум серед сум модулів елементів діагоналей (паралельних побічній): {min_diag_sum}")

Початкова матриця:
[[  1   2  -3   4   5   6   7   8   9  10  11  12]
 [  2   3   4   5   6   7   8   9  10  11  12  13]
 [  3   4   5   6   7   8   9  10  11  12  13  14]
 [  4   5   6   7   8   9  10  11  12  13  14  15]
 [  5   6   7   8   9  10  11  12  13  14  15  16]
 [  6   7   8   9  10 -11  12  13  14  15  16  17]
 [  7   8   9  10  11  12  13  14  15  16  17  18]
 [  8   9  10  11  12  13  14  15  16  17  18  19]
 [  9  10  11  12  13  14  15  16  17  18  19  20]
 [ 10  11  12  13  14  15  16  17  18  19  20  21]
 [ 11  12 -13  14  15  16  17  18  19  20  21  22]
 [ 12  13  14  15  16  17  18  19  20  21  22  23]]

1) Суми в стовпцях без від'ємних елементів: [ 78  90 114 126 150 162 174 186 198 210]
Загальна сума елементів у цих стовпцях: 1488

2) Мінімум серед сум модулів елементів діагоналей (паралельних побічній): 1
